Numerous improvements
curityio/flask-of-oil pull request #16
Opened 2022-07-02 00:11 UTC by dangoscomb

Hi

I have made a number of improvements so that this fits in our environment. I have tried to maintain backwards compatibility but lack of unit tests has made it a little difficult so this would probably need a little testing.

Changes made:

- allow list of audiences to be checked, not just single
- configure_with_multiple_jwt_issuers() can now be called with a list of dicts for issuers, instead of strings, in the format:
```python
{
  'url': str, # complete url to the jwks file
  'name': str, # should match the iss claim,
  'audience': str|list[str] # audiences to allow from this issuer
}
```
- _authorize() (and calling functions) now accept an optional audience parameter allowing checks for a specific aud on decorators, etc
- claims that are lists can now be checked with _authorize()
- prevent exception if scope claim is not present

2022-08-29 08:48 UTC, travisspencer requested changes

2022-08-29 08:48 UTC, travisspencer commented on flask_of_oil/jwt_validator.py
> +        if len(set(self.aud)&set(aud)) == 0:
whitespace around the `&` operator would be preferable IMO

2022-08-29 08:48 UTC, travisspencer commented on flask_of_oil/oauth_filter.py
> +                self.validators[issuer['name']] = JwtValidator(issuer['url'], issuer['name'], issuer['audience'],
what says the issuer is in the `name` entry of the dictionary? Similar question for `url` and `audience`.

2022-08-29 08:48 UTC, travisspencer commented on flask_of_oil/oauth_filter.py
> +            if len(set(endpoint_audience)&set(token_claims['aud'])) == 0:
whitespace before/after `&`.

2022-08-29 08:48 UTC, travisspencer commented on flask_of_oil/oauth_filter.py
> +            if endpoint_claims[claim] is not None:
Does it make sense to factor this out? It's getting to be a lot of nesting here.

2022-08-29 08:48 UTC, travisspencer commented on flask_of_oil/oauth_filter.py
> +                        if len(set(token_claims[claim])&set(endpoint_claims[claim])) == 0:
whitespace `&`

2022-09-05 09:04 UTC, mtrojanowski requested changes
Hey @dangoscomb,

Thanks for your contribution. Some nice additions to the library!

You made a good point about the missing tests so we've recently added some basic coverage. Are you able to add tests for the changes that you've made?

There are some minor comments to the PR left by me and Travis. Can you have a look at these also?

2022-09-05 09:04 UTC, mtrojanowski commented on flask_of_oil/oauth_filter.py
> +    def configure_with_multiple_jwt_issuers(self, issuers, audience=None, scopes=None):
Maybe there should be a check that if the issuer is a string, then the audience is required. Currently, the validator can be configured with a `None` audience.

2022-09-05 09:04 UTC, mtrojanowski commented on flask_of_oil/oauth_filter.py
> +                self.validators[issuer['name']] = JwtValidator(issuer['url'], issuer['name'], issuer['audience'],
Can you update the README and describe that structure? I wonder whether there should be some checks if all the necessary elements of the dictionary are present.

Also, I'm not quite sold yet on the idea that the audience is a per-issuer setting. Is it because you have different URLs/identifiers for the same API?

2025-09-17 14:29 UTC, closed without merging